# Generated by Django 2.2.13 on 2020-06-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SDUser',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('profile_image_URL', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(null=True)),
                ('email_verified', models.BooleanField()),
                ('locale', models.CharField(max_length=30)),
                ('UUid', models.UUIDField(null=True)),
            ],
        ),
    ]
