# Generated by Django 2.2.8 on 2020-06-30 20:28

import auth2.enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sduser',
            name='role',
            field=models.CharField(choices=[(auth2.enum.Roles('Restaurant Owner'), 'Restaurant Owner'), (auth2.enum.Roles('Basic User'), 'Basic User')], default=auth2.enum.Roles('Basic User'), max_length=5),
        ),
    ]
