# Generated by Django 2.2.8 on 2020-06-30 21:19

import auth2.enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0002_sduser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sduser',
            name='role',
            field=models.CharField(choices=[(auth2.enum.Roles('Restaurant Owner'), 'Restaurant Owner'), (auth2.enum.Roles('Basic User'), 'Basic User')], max_length=5),
        ),
    ]
