# Generated by Django 2.2.8 on 2020-07-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0003_auto_20200630_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sduser',
            name='role',
            field=models.CharField(choices=[('RO', 'Restaurant Owner'), ('BU', 'Basic User')], default='BU', max_length=5),
        ),
    ]
