# Generated by Django 2.2.8 on 2020-07-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0004_auto_20200708_2342'),
        ('auth2', '0004_auto_20200709_1124'),
    ]

    operations = [
    ]
