# Generated by Django 2.2.8 on 2020-07-05 17:35

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=40)),
                ('cuisine', models.CharField(max_length=30)),
                ('pricepoint', models.CharField(max_length=30)),
                ('twitter', models.CharField(max_length=40)),
                ('instagram', models.CharField(max_length=40)),
                ('bio', models.TextField()),
                ('GEO_location', models.CharField(max_length=20)),
                ('external_delivery_link', models.CharField(max_length=30)),
            ],
        ),
    ]
