# Generated by Django 2.2.8 on 2020-07-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='GEO_location',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='external_delivery_link',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='instagram',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='twitter',
            field=models.CharField(max_length=60),
        ),
    ]
