# Generated by Django 2.2.8 on 2020-07-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RO', '0002_auto_20200705_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
