# Generated by Django 2.2.8 on 2020-07-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RO', '0003_auto_20200707_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='GEO_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='external_delivery_link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='instagram',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='twitter',
            field=models.CharField(max_length=100),
        ),
    ]
