# Generated by Django 2.2.8 on 2020-07-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RO', '0004_auto_20200708_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cover_photo_url',
            field=models.CharField(default='https://www.nautilusplus.com/content/uploads/2016/08/Pexel_junk-food.jpeg', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo_url',
            field=models.CharField(default='https://d1csarkz8obe9u.cloudfront.net/posterpreviews/diner-restaurant-logo-design-template-0899ae0c7e72cded1c0abc4fe2d76ae4_screen.jpg?ts=1561476509', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='GEO_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='external_delivery_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='instagram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='twitter',
            field=models.CharField(max_length=200),
        ),
    ]
