# Generated by Django 2.2.15 on 2020-08-10 06:33

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTag',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('PR', 'Promotion'), ('FR', 'Food Restriction'), ('CU', 'Cuisine'), ('DI', 'Dish')], max_length=4)),
                ('value', models.CharField(max_length=50)),
                ('foods', djongo.models.fields.ListField(blank=True, default=[])),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=40)),
                ('cuisine', models.CharField(max_length=30)),
                ('pricepoint', models.CharField(choices=[('Low', '$'), ('Medium', '$$'), ('High', '$$$')], max_length=10)),
                ('twitter', models.CharField(blank=True, max_length=200)),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(null=True)),
                ('GEO_location', models.CharField(max_length=200)),
                ('external_delivery_link', models.CharField(blank=True, max_length=200)),
                ('cover_photo_url', models.CharField(default='https://storage.googleapis.com/default-assets/cover.jpg', max_length=200)),
                ('logo_url', models.CharField(default='https://storage.googleapis.com/default-assets/logo.jpg', max_length=200)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('owner_name', models.CharField(blank=True, max_length=50)),
                ('owner_story', models.CharField(blank=True, max_length=3000)),
                ('owner_picture_url', models.CharField(blank=True, max_length=200)),
                ('categories', djongo.models.fields.ListField(blank=True, default=[])),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('restaurant_id', models.CharField(editable=False, max_length=24)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('picture', models.CharField(blank=True, default='https://storage.googleapis.com/default-assets/no-image.png', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tags', djongo.models.fields.ListField(blank=True, default=[])),
                ('specials', models.CharField(blank=True, max_length=51)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'unique_together': {('name', 'restaurant_id')},
            },
        ),
    ]
