# Generated by Django 2.2.8 on 2020-07-09 19:33

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='tags',
            field=djongo.models.fields.ListField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualtag',
            name='foods',
            field=djongo.models.fields.ListField(default=[]),
            preserve_default=False,
        ),
    ]
