# Generated by Django 2.2.8 on 2020-07-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualtag',
            name='category',
            field=models.CharField(choices=[('promo', 'promo'), ('allergy', 'allergy'), ('cuisine', 'cuisine'), ('dish', 'dish')], max_length=20),
        ),
    ]
