# Generated by Django 2.2.8 on 2020-07-10 03:23

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='tags',
            field=djongo.models.fields.ListField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='manualtag',
            name='foods',
            field=djongo.models.fields.ListField(blank=True, default=[]),
        ),
    ]
