# Generated by Django 2.2.8 on 2020-07-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_food_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
        migrations.AlterUniqueTogether(
            name='food',
            unique_together={('name', 'restaurant_id')},
        ),
    ]
