# Generated by Django 2.2.8 on 2020-07-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200709_1533'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='food',
            unique_together=set(),
        ),
    ]
