# Generated by Django 2.2.8 on 2020-07-08 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20200707_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualtag',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Food'),
        ),
    ]
